
from project_willy.text_fields.menu_text.notes_book_menu_text.notes_menu_main_text import NotesMenuText
from project_willy.text_fields.menu_text.notes_book_menu_text.notes_menu_add_text import AddNotesMenuText
from project_willy.text_fields.menu_text.notes_book_menu_text.notes_menu_change_text import ChangeNotesMenuText
from project_willy.text_fields.menu_text.notes_book_menu_text.notes_menu_show_text import ShowNotesMenuText
