
from project_willy.text_fields.menu_text.general_text import GeneralText
from project_willy.text_fields.menu_text.main_menu_text import MainMenuText
from project_willy.text_fields.menu_text.start_text import StartText
