
from project_willy.text_fields.menu_text.records_book_menu_text.records_book_menu_main_text import RecordsBookMenuText
from project_willy.text_fields.menu_text.records_book_menu_text.records_book_menu_add_text import AddRecordMenuText
from project_willy.text_fields.menu_text.records_book_menu_text.records_book_menu_change_text import ChangeRecordMenuText
from project_willy.text_fields.menu_text.records_book_menu_text.records_book_menu_export_text import ExportMenuText
from project_willy.text_fields.menu_text.records_book_menu_text.records_book_menu_import_text import ImportMenuText
from project_willy.text_fields.menu_text.records_book_menu_text.records_book_menu_show_text import ShowRecordsMenuText
