
from project_willy.settings.representation_settings.menu_representation_settings import MenuReprSettings
from project_willy.settings.representation_settings.records_representation_settings import RecordReprSettings, RecordsBookReprSettings
from project_willy.settings.representation_settings.notes_representation_settings import NotesReprSettings, NotesBookReprSettings
