
from project_willy.menu.main_menu_options.notes_book_menu_options.notes_menu_add import AddNotesMenu
from project_willy.menu.main_menu_options.notes_book_menu_options.notes_menu_change import ChangeNotesMenu
from project_willy.menu.main_menu_options.notes_book_menu_options.notes_menu_show import ShowNotesMenu
