
from project_willy.menu.main_menu_options.records_book_menu_options.records_book_menu_add import AddRecordMenu
from project_willy.menu.main_menu_options.records_book_menu_options.records_book_menu_change import ChangeRecordMenu
from project_willy.menu.main_menu_options.records_book_menu_options.records_book_menu_export import ExportMenu
from project_willy.menu.main_menu_options.records_book_menu_options.records_book_menu_import import ImportMenu
from project_willy.menu.main_menu_options.records_book_menu_options.records_book_menu_show import ShowRecordsMenu
